//==============================================================================
// Hierarchical dofile generated by Conformal LEC
// Version: 19.10-s300 (24-Aug-2019) (64 bit executable)
//------------------------------------------------------------------------------
// The command 'set module property' sets the instance context for the current
// root module. It is intended only for hierarchical comparison, and should
// not be modified by the user.
//==============================================================================

//==============================================================================
// Comienzo con los dos modulos que no han sido genrados de forma automatica
// debido a que tienen distintos puertos el RTL (Golden) y el Netlist (Revised)
//==============================================================================
set system mode setup
set root module exu -Both
set module property -instance /swerv/exu -Golden
set module property -instance /swerv/exu -Revised
add pin equivalences active_clk RC_CG_GCLK_PORT -revised
add pin equivalences active_clk RC_CG_GCLK_PORT_1 -revised
report black box -NOHidden
set system mode lec
add compared points -all
compare
save hier_compare result
set system mode setup
add black box exu -module -hier -Golden
add black box exu -module -hier -Revised
set root module dec_decode_ctl -Both
set module property -instance /swerv/dec/dec_decode_ctl -Golden
set module property -instance /swerv/dec/dec_decode_ctl -Revised
add pin equivalences active_clock RC_CG_GCLK_PORT -revised
add pin equivalences active_clock RC_CG_GCLK_PORT_1 -revised
report black box -NOHidden
set system mode lec
add compared points -all
compare
save hier_compare result
set system mode setup
add black box dec_decode_ctl -module -hier -Golden
add black box dec_decode_ctl -module -hier -Revised

set system mode setup
// Comparing module 'ifu_bp_ctl'
set root module ifu_bp_ctl -Golden
set root module ifu_bp_ctl -Revised
set module property -instance /swerv/ifu/bp -Golden
set module property -instance /swerv/ifu_bp -Revised
report black box -NOHidden
set system mode lec
add compared points -all
compare
save hier_compare result
set system mode setup
add black box ifu_bp_ctl -module -hier -Golden
add black box ifu_bp_ctl -module -hier -Revised
// Comparing module 'ifu_aln_ctl'
set root module ifu_aln_ctl -Golden
set root module ifu_aln_ctl -Revised
set module property -instance /swerv/ifu/aln -Golden
set module property -instance /swerv/ifu_aln -Revised
report black box -NOHidden
set system mode lec
add compared points -all
compare
save hier_compare result
set system mode setup
add black box ifu_aln_ctl -module -hier -Golden
add black box ifu_aln_ctl -module -hier -Revised
// Comparing module 'ifu_mem_ctl'
set root module ifu_mem_ctl -Golden
set root module ifu_mem_ctl -Revised
set module property -instance /swerv/ifu/mem_ctl -Golden
set module property -instance /swerv/ifu_mem_ctl -Revised
report black box -NOHidden
set system mode lec
add compared points -all
compare
save hier_compare result
set system mode setup
add black box ifu_mem_ctl -module -hier -Golden
add black box ifu_mem_ctl -module -hier -Revised
// Comparing module 'lsu_bus_intf'
set root module lsu_bus_intf -Golden
set root module lsu_bus_intf -Revised
set module property -instance /swerv/lsu/bus_intf -Golden
set module property -instance /swerv/lsu/bus_intf -Revised
report black box -NOHidden
set system mode lec
add compared points -all
compare
save hier_compare result
set system mode setup
add black box lsu_bus_intf -module -hier -Golden
add black box lsu_bus_intf -module -hier -Revised
// Comparing module 'lsu'
set root module lsu -Golden
set root module lsu -Revised
set module property -instance /swerv/lsu -Golden
set module property -instance /swerv/lsu -Revised
report black box -NOHidden
set system mode lec
add compared points -all
compare
save hier_compare result
set system mode setup
add black box lsu -module -hier -Golden
add black box lsu -module -hier -Revised
// Comparing module 'dma_ctrl'
set root module dma_ctrl -Golden
set root module dma_ctrl -Revised
set module property -instance /swerv/dma_ctrl -Golden
set module property -instance /swerv/dma_ctrl -Revised
report black box -NOHidden
set system mode lec
add compared points -all
compare
save hier_compare result
set system mode setup
add black box dma_ctrl -module -hier -Golden
add black box dma_ctrl -module -hier -Revised
// Comparing module 'swerv'
set root module swerv -Golden
set root module swerv -Revised
set module property -instance /swerv -Golden
set module property -instance /swerv -Revised
report black box -NOHidden
set system mode lec
add compared points -all
compare
save hier_compare result
set system mode setup
add black box swerv -module -hier -Golden
add black box swerv -module -hier -Revised
// Comparing module 'mem'
set root module mem -Golden
set root module mem -Revised
set module property -instance /mem -Golden
set module property -instance /mem -Revised
report black box -NOHidden
set system mode lec
add compared points -all
compare
save hier_compare result
set system mode setup
add black box mem -module -hier -Golden
add black box mem -module -hier -Revised
// Comparing module 'dmi_wrapper'
set root module dmi_wrapper -Golden
set root module dmi_wrapper -Revised
set module property -instance /dmi_wrapper -Golden
set module property -instance /dmi_wrapper -Revised
report black box -NOHidden
set system mode lec
add compared points -all
compare
save hier_compare result
set system mode setup
add black box dmi_wrapper -module -hier -Golden
add black box dmi_wrapper -module -hier -Revised
// Root modules
// Comparing module 'swerv_wrapper'
set root module swerv_wrapper -Golden
set root module swerv_wrapper -Revised
set module property -instance / -Golden
set module property -instance / -Revised
report black box -NOHidden
set system mode lec
add compared points -all
compare
save hier_compare result
set system mode setup
report hier_compare result > hier_compare.results
report hier_compare result -Non_equivalent >> hier_compare.results
report hier_compare result -Abort >> hier_compare.results
report hier_compare result -Uncompared >> hier_compare.results
// _END_OF_LEC_HIERARCHICAL_DOFILE_
